version: 3

tasks:
  run:
    cmds:
      # - go run ./main.go --file=.tools/sample.grapqhl.yml --env .tools/gqlenv.yml --line {{.CLI_ARGS}}
      - npm start -- graphql -f .tools/sample.grapqhl.yml -e .tools/gqlenv.yml  -l 10
